### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by hirbod** [rafaylik/stickymate#1]
Hey,

this library looks stunning and the demonstration looks awesome. What a bummer it only has 2 stars.

I think you should really publish this as a package on NPM and make it usable with bundlers and imports etc. This would benefit for the ecosystem and your libraries popularity.

**Comment by michaelrafailyk** [comment]
Hello Hirbod!
Good idea, thank you for the advise, i’ll figure out how it works!

**Comment by michaelrafailyk** [comment]
Done
