### ISSUE TITLE
Support for events

### ISSUE THREAD

**Issue by hirbod** [rafaylik/stickymate#2]
In order to trigger videos for example. (autoplay when they have zoomed to fullwidth for example)

**Comment by hirbod** [comment]
I've ended up using a mix with IntersectionObserver and MutationObserver

**Comment by michaelrafailyk** [comment]
> I've ended up using a mix with IntersectionObserver and MutationObserver

Interesting about Intersection Observer for catching elements just not sure that browsers are ready for it now, especially Safari.

Also people talk that IO is not good for scroll-based animation because update time is not enough fast. Need to read more about it.
