### ISSUE TITLE
Support for snapping

### ISSUE THREAD

**Issue by hirbod** [rafaylik/stickymate#3]
It would be cool if a started animation (lets say scale from 0.75 to 1) could be snapped once triggered. Currently, it will stop where scroll/momentum ends and sometimes lead to weird positioning. Do you think something like this can be possible, maybe even with css snapping?

**Comment by rafaylik** [comment]
I think it’s possible to expand, for example, “data-classes”, and add/remove a css classes on the specified key position. I have another script for this functionality, but it is easy to expand this one.

**Comment by hirbod** [comment]
I did a trick on my setup for now. I've setup 

(pseudo): `0vh: 0.75, 1vh: 1`
 
and added a class to the my animated div with css transition set to 1 second. 
It works great without any issues.

**Comment by luco** [comment]
@Hirbod Can you post an example?

**Comment by michaelrafailyk** [comment]
Since [v1.2.5](https://github.com/michaelrafailyk/stickymate/releases/tag/v1.2.5) the library support `data-classes` so I suppose it do the same work.
